title: XiangyuWEN's Homepage
page-top-title: Xiangyu Wen's Homepage
top-section-bg-text: WHO DARES WINS.
home-subtitle: Xiangyu WEN&ensp;|&ensp;温翔宇
copyright-text: '&copy; XiangyuWen 2022-2026. All Rights Reserved.'
